# Site settings
title: Vasil Molaliyski
description: 'and his little corner on the internet.'
url: 'https://TalkinWhip.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Vasil Molaliyski'
  email: vasil@molaliyski.com
  twitter_username: talkinwhip #'@talkinwhip@qoto.org'
  facebook_username: talkin-whip:matrix.org
  github_username:  TalkinWhip
  linkedin_username:  vasil-molaliyski

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
